// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../docs/index.mdx?collection=docs"), "bootup/introduction.mdx": () => import("../docs/bootup/introduction.mdx?collection=docs"), "bootup/migrate-to-polar.mdx": () => import("../docs/bootup/migrate-to-polar.mdx?collection=docs"), "features/analytics.mdx": () => import("../docs/features/analytics.mdx?collection=docs"), "features/custom-fields.mdx": () => import("../docs/features/custom-fields.mdx?collection=docs"), "features/customer-management.mdx": () => import("../docs/features/customer-management.mdx?collection=docs"), "features/customer-portal.mdx": () => import("../docs/features/customer-portal.mdx?collection=docs"), "features/discounts.mdx": () => import("../docs/features/discounts.mdx?collection=docs"), "features/finance-payouts.mdx": () => import("../docs/features/finance-payouts.mdx?collection=docs"), "features/integrations.mdx": () => import("../docs/features/integrations.mdx?collection=docs"), "features/orders-subscriptions.mdx": () => import("../docs/features/orders-subscriptions.mdx?collection=docs"), "features/products.mdx": () => import("../docs/features/products.mdx?collection=docs"), "features/refunds.mdx": () => import("../docs/features/refunds.mdx?collection=docs"), "features/seat-based-pricing.mdx": () => import("../docs/features/seat-based-pricing.mdx?collection=docs"), "features/trials.mdx": () => import("../docs/features/trials.mdx?collection=docs"), "merchant-of-record/acceptable-use.mdx": () => import("../docs/merchant-of-record/acceptable-use.mdx?collection=docs"), "merchant-of-record/account-reviews.mdx": () => import("../docs/merchant-of-record/account-reviews.mdx?collection=docs"), "merchant-of-record/fees.mdx": () => import("../docs/merchant-of-record/fees.mdx?collection=docs"), "merchant-of-record/introduction.mdx": () => import("../docs/merchant-of-record/introduction.mdx?collection=docs"), "merchant-of-record/supported-countries.mdx": () => import("../docs/merchant-of-record/supported-countries.mdx?collection=docs"), "integrate/authentication.mdx": () => import("../docs/integrate/authentication.mdx?collection=docs"), "integrate/customer-state.mdx": () => import("../docs/integrate/customer-state.mdx?collection=docs"), "integrate/framework-adapters.mdx": () => import("../docs/integrate/framework-adapters.mdx?collection=docs"), "integrate/framework-guides.mdx": () => import("../docs/integrate/framework-guides.mdx?collection=docs"), "integrate/model-context-protocol-mcp.mdx": () => import("../docs/integrate/model-context-protocol-mcp.mdx?collection=docs"), "integrate/oauth-2.mdx": () => import("../docs/integrate/oauth-2.mdx?collection=docs"), "integrate/sandbox-environment.mdx": () => import("../docs/integrate/sandbox-environment.mdx?collection=docs"), "integrate/sdks.mdx": () => import("../docs/integrate/sdks.mdx?collection=docs"), "integrate/webhooks.mdx": () => import("../docs/integrate/webhooks.mdx?collection=docs"), }),
};
export default browserCollections;