// @ts-nocheck
import * as __fd_glob_44 from "../docs/openapi/update-item.mdx?collection=docs"
import * as __fd_glob_43 from "../docs/openapi/openapi.mdx?collection=docs"
import * as __fd_glob_42 from "../docs/openapi/index.mdx?collection=docs"
import * as __fd_glob_41 from "../docs/openapi/health.mdx?collection=docs"
import * as __fd_glob_40 from "../docs/openapi/get-me.mdx?collection=docs"
import * as __fd_glob_39 from "../docs/openapi/generate-files.mdx?collection=docs"
import * as __fd_glob_38 from "../docs/openapi/delete-item.mdx?collection=docs"
import * as __fd_glob_37 from "../docs/openapi/create-openapi.mdx?collection=docs"
import * as __fd_glob_36 from "../docs/openapi/create-item.mdx?collection=docs"
import * as __fd_glob_35 from "../docs/openapi/api-page.mdx?collection=docs"
import * as __fd_glob_34 from "../docs/merchant-of-record/supported-countries.mdx?collection=docs"
import * as __fd_glob_33 from "../docs/merchant-of-record/introduction.mdx?collection=docs"
import * as __fd_glob_32 from "../docs/merchant-of-record/fees.mdx?collection=docs"
import * as __fd_glob_31 from "../docs/merchant-of-record/account-reviews.mdx?collection=docs"
import * as __fd_glob_30 from "../docs/merchant-of-record/acceptable-use.mdx?collection=docs"
import * as __fd_glob_29 from "../docs/integrate/webhooks.mdx?collection=docs"
import * as __fd_glob_28 from "../docs/integrate/sdks.mdx?collection=docs"
import * as __fd_glob_27 from "../docs/integrate/sandbox-environment.mdx?collection=docs"
import * as __fd_glob_26 from "../docs/integrate/oauth-2.mdx?collection=docs"
import * as __fd_glob_25 from "../docs/integrate/model-context-protocol-mcp.mdx?collection=docs"
import * as __fd_glob_24 from "../docs/integrate/framework-guides.mdx?collection=docs"
import * as __fd_glob_23 from "../docs/integrate/framework-adapters.mdx?collection=docs"
import * as __fd_glob_22 from "../docs/integrate/customer-state.mdx?collection=docs"
import * as __fd_glob_21 from "../docs/integrate/authentication.mdx?collection=docs"
import * as __fd_glob_20 from "../docs/features/trials.mdx?collection=docs"
import * as __fd_glob_19 from "../docs/features/seat-based-pricing.mdx?collection=docs"
import * as __fd_glob_18 from "../docs/features/refunds.mdx?collection=docs"
import * as __fd_glob_17 from "../docs/features/products.mdx?collection=docs"
import * as __fd_glob_16 from "../docs/features/orders-subscriptions.mdx?collection=docs"
import * as __fd_glob_15 from "../docs/features/integrations.mdx?collection=docs"
import * as __fd_glob_14 from "../docs/features/finance-payouts.mdx?collection=docs"
import * as __fd_glob_13 from "../docs/features/discounts.mdx?collection=docs"
import * as __fd_glob_12 from "../docs/features/customer-portal.mdx?collection=docs"
import * as __fd_glob_11 from "../docs/features/customer-management.mdx?collection=docs"
import * as __fd_glob_10 from "../docs/features/custom-fields.mdx?collection=docs"
import * as __fd_glob_9 from "../docs/features/analytics.mdx?collection=docs"
import * as __fd_glob_8 from "../docs/bootup/migrate-to-polar.mdx?collection=docs"
import * as __fd_glob_7 from "../docs/bootup/introduction.mdx?collection=docs"
import * as __fd_glob_6 from "../docs/index.mdx?collection=docs"
import { default as __fd_glob_5 } from "../docs/openapi/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../docs/merchant-of-record/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../docs/integrate/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../docs/features/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../docs/bootup/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "docs", {"meta.json": __fd_glob_0, "bootup/meta.json": __fd_glob_1, "features/meta.json": __fd_glob_2, "integrate/meta.json": __fd_glob_3, "merchant-of-record/meta.json": __fd_glob_4, "openapi/meta.json": __fd_glob_5, }, {"index.mdx": __fd_glob_6, "bootup/introduction.mdx": __fd_glob_7, "bootup/migrate-to-polar.mdx": __fd_glob_8, "features/analytics.mdx": __fd_glob_9, "features/custom-fields.mdx": __fd_glob_10, "features/customer-management.mdx": __fd_glob_11, "features/customer-portal.mdx": __fd_glob_12, "features/discounts.mdx": __fd_glob_13, "features/finance-payouts.mdx": __fd_glob_14, "features/integrations.mdx": __fd_glob_15, "features/orders-subscriptions.mdx": __fd_glob_16, "features/products.mdx": __fd_glob_17, "features/refunds.mdx": __fd_glob_18, "features/seat-based-pricing.mdx": __fd_glob_19, "features/trials.mdx": __fd_glob_20, "integrate/authentication.mdx": __fd_glob_21, "integrate/customer-state.mdx": __fd_glob_22, "integrate/framework-adapters.mdx": __fd_glob_23, "integrate/framework-guides.mdx": __fd_glob_24, "integrate/model-context-protocol-mcp.mdx": __fd_glob_25, "integrate/oauth-2.mdx": __fd_glob_26, "integrate/sandbox-environment.mdx": __fd_glob_27, "integrate/sdks.mdx": __fd_glob_28, "integrate/webhooks.mdx": __fd_glob_29, "merchant-of-record/acceptable-use.mdx": __fd_glob_30, "merchant-of-record/account-reviews.mdx": __fd_glob_31, "merchant-of-record/fees.mdx": __fd_glob_32, "merchant-of-record/introduction.mdx": __fd_glob_33, "merchant-of-record/supported-countries.mdx": __fd_glob_34, "openapi/api-page.mdx": __fd_glob_35, "openapi/create-item.mdx": __fd_glob_36, "openapi/create-openapi.mdx": __fd_glob_37, "openapi/delete-item.mdx": __fd_glob_38, "openapi/generate-files.mdx": __fd_glob_39, "openapi/get-me.mdx": __fd_glob_40, "openapi/health.mdx": __fd_glob_41, "openapi/index.mdx": __fd_glob_42, "openapi/openapi.mdx": __fd_glob_43, "openapi/update-item.mdx": __fd_glob_44, });